defaults:
  - dataset: drift_sim_v3_1m
  - model: straw_model
  - user_settings: user_settings
  - _self_

experiment:
  name: straw_tracknet_v3_1m

training:
  seed: 42
  batch_size: 8000
  max_epochs: 1000
  num_workers: 8
  shuffle: true
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  matmul_precision: high
  accumulate_grad_batches: 4
  gradient_clip_val: 1.0
  early_stopping_patience: 20
  log_every_n_steps: 20
  check_val_every_n_epoch: 1
  resume_from: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0

logging:
  output_dir: ${hydra:run.dir}/logs
